apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name:  {{ template "name" . }}
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Release.Name }}.jomacsit.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ template "name" . }}
            port:
              number: 80