apiVersion: v1
kind: Service
metadata:
  name:  {{ template "name" . }}
spec:
  type: NodePort
  selector:
    name:  {{ template "name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80